version: '3'
services:
  jekyll-serve:
    image: jekyll/jekyll
    command: jekyll serve --livereload --watch --force_polling
    volumes:
      - ".:/srv/jekyll"
    ports:
      - "4000:4000"
      - "35729:35729"   # LiveReload
